var ccb_resources = [
    {type:'image', src:"img/effect.png"},
    {type:'ccbi', src:"ccbs/tableView.ccbi"},
    {type:'plist', src:"img/loading.plist"},
    {type:'ccbi', src:"ccbs/MagicCircle.ccbi"},
    {type:'plist', src:"img/hero.plist"},
    {type:'ccbi', src:"ccbs/UI.ccbi"},
    {type:'image', src:"img/number.png"},
    {type:'image', src:"img/ui.png"},
    {type:'ccbi', src:"ccbs/HeroCheckout.ccbi"},
    {type:'ccbi', src:"ccbs/touchLayer.ccbi"},
    {type:'image', src:"img/loading.png"},
    {type:'ccbi', src:"ccbs/tableViewCell.ccbi"},
    {type:'ccbi', src:"ccbs/Checkout.ccbi"},
    {type:'image', src:"img/checkout.png"},
    {type:'image', src:"img/checkoutbg.png"},
    {type:'plist', src:"img/effect.plist"},
    {type:'image', src:"img/gamescenebg.jpg"},
    {type:'plist', src:"img/checkout.plist"},
    {type:'plist', src:"img/ui.plist"},
    {type:'image', src:"img/hero.png"},
    {type:'ccbi', src:"ccbs/GameScene.ccbi"},
    {type:'ccbi', src:"ccbs/Hero.ccbi"},
    {type:'ccbi', src:"ccbs/LoadingScene.ccbi"},
    {type:'ccbi', src:"ccbs/ChangeMoster.ccbi"},
    {type:'plist', src:"img/number.plist"},
];
